// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG4V3HQi5fsWG3mC7jSJqxEvokMxm6GIk',
    appId: '1:833130301180:web:da754f179024d1a304f979',
    messagingSenderId: '833130301180',
    projectId: 'ravish-ae358',
    authDomain: 'ravish-ae358.firebaseapp.com',
    storageBucket: 'ravish-ae358.appspot.com',
    measurementId: 'G-0T2XEJ8JST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoidxeTKZ3uWjPGWIPyrUnjziLujqI3q0',
    appId: '1:833130301180:android:8c2ec321bfe2fb7104f979',
    messagingSenderId: '833130301180',
    projectId: 'ravish-ae358',
    storageBucket: 'ravish-ae358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigTkFC6BmldxMUdY2m1yZTWI4-0G2BP8',
    appId: '1:833130301180:ios:cb070dc1bec4748d04f979',
    messagingSenderId: '833130301180',
    projectId: 'ravish-ae358',
    storageBucket: 'ravish-ae358.appspot.com',
    iosBundleId: 'com.adeelsafdar.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCigTkFC6BmldxMUdY2m1yZTWI4-0G2BP8',
    appId: '1:833130301180:ios:0b74bb990bb7fca104f979',
    messagingSenderId: '833130301180',
    projectId: 'ravish-ae358',
    storageBucket: 'ravish-ae358.appspot.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );
}
