// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFoMW342QwmgHorttjOcKYF3fN8O2jqA4',
    appId: '1:1046501087671:web:597e98dab5e4bdf7b83032',
    messagingSenderId: '1046501087671',
    projectId: 'auth-72203',
    authDomain: 'auth-72203.firebaseapp.com',
    storageBucket: 'auth-72203.appspot.com',
    measurementId: 'G-WJTKQ4KQ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkPSHAs0sPPx-2iAl_APzquIQXF0X9Geo',
    appId: '1:1046501087671:android:3c51208c8fec93f6b83032',
    messagingSenderId: '1046501087671',
    projectId: 'auth-72203',
    storageBucket: 'auth-72203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw77vzKOpBg8Z285RxIc67Y2gByDfs_wg',
    appId: '1:1046501087671:ios:63ef412c9a34f4d6b83032',
    messagingSenderId: '1046501087671',
    projectId: 'auth-72203',
    storageBucket: 'auth-72203.appspot.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw77vzKOpBg8Z285RxIc67Y2gByDfs_wg',
    appId: '1:1046501087671:ios:63ef412c9a34f4d6b83032',
    messagingSenderId: '1046501087671',
    projectId: 'auth-72203',
    storageBucket: 'auth-72203.appspot.com',
    iosBundleId: 'com.adeelsafdar.loginsignup.loginSignup',
  );
}
